# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bank_pb2 as bank__pb2


class BankStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetBalance = channel.unary_unary(
        '/proto.bank.Bank/GetBalance',
        request_serializer=bank__pb2.GetBalanceRequest.SerializeToString,
        response_deserializer=bank__pb2.GetBalanceResponse.FromString,
        )
    self.Pay = channel.unary_unary(
        '/proto.bank.Bank/Pay',
        request_serializer=bank__pb2.PayRequest.SerializeToString,
        response_deserializer=bank__pb2.PayResponse.FromString,
        )
    self.Transfer = channel.unary_unary(
        '/proto.bank.Bank/Transfer',
        request_serializer=bank__pb2.TransferRequest.SerializeToString,
        response_deserializer=bank__pb2.TransferResponse.FromString,
        )
    self.KillServer = channel.unary_unary(
        '/proto.bank.Bank/KillServer',
        request_serializer=bank__pb2.KillServerRequest.SerializeToString,
        response_deserializer=bank__pb2.KillServerResponse.FromString,
        )


class BankServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Transfer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def KillServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=bank__pb2.GetBalanceRequest.FromString,
          response_serializer=bank__pb2.GetBalanceResponse.SerializeToString,
      ),
      'Pay': grpc.unary_unary_rpc_method_handler(
          servicer.Pay,
          request_deserializer=bank__pb2.PayRequest.FromString,
          response_serializer=bank__pb2.PayResponse.SerializeToString,
      ),
      'Transfer': grpc.unary_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=bank__pb2.TransferRequest.FromString,
          response_serializer=bank__pb2.TransferResponse.SerializeToString,
      ),
      'KillServer': grpc.unary_unary_rpc_method_handler(
          servicer.KillServer,
          request_deserializer=bank__pb2.KillServerRequest.FromString,
          response_serializer=bank__pb2.KillServerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.bank.Bank', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
